### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by gorkemyontem** [strapi-community/strapi-provider-upload-google-cloud-storage#121]
Sorry to open this ambiguous issue. Unfortunately, I don't have steps to reproduce. 

I have a strapi app on the production environment and I'm using GCP-GCS to store the images. 
Recently I have noticed that a few images are missing from the media library and also from the fields.  When I check the GCS I couldn't locate the images.

![image](https://user-images.githubusercontent.com/8965495/150758253-be98c49e-a9ce-4df6-897b-294e19853494.png)

Do you have any idea? Or are there anybody else with this issue?

**Comment by callum-gander** [comment]
Not getting the exact same error, but images aren't loading in the media library, the links still lead to the images but for whatever reason they aren't being downloaded and displayed by strapi

**Comment by eveningforgery** [comment]
Had to do this, now it works perfectly.

https://cloud.google.com/storage/docs/access-control/making-data-public#buckets

Maybe someone should update the doc.

**Comment by ancashoria** [comment]
My issue is similar, but weirder. Some images have disappeared from my bucket and I don't know why. Strapi Media Library still knows about them, but it can't load them since they no longer exist in the bucket.

I really don't know where to stard debugging this.
I'm using Digital Ocean Spaces Object Storage (S3 compatible) and strapi 5.13.0 but I've seen this happen on previous versions too.
