### ISSUE TITLE
Support for non public non-public read access

### ISSUE THREAD

**Issue by danielduckworth** [strapi-community/strapi-provider-upload-google-cloud-storage#148]
**Is your feature request related to a problem? Please describe.**
When using a non-public bucket, images can be uploaded but they cannot be read by the Strapi frontend application.

**Describe the solution you'd like**
Use an API that supports authenticated read access to images.

**Additional context**
The content to be uploaded to storage needs to be secure and only accessible to authenticated users.

**Comment by nikita-fuchs** [comment]
hey @Lith , does the plugin work differently from strapi's standard upload mechanism? I can't imagine that strapi stores and serves URLs to publicly available files I guess, so I wonder why that approach was used for this plugin instead of fetching the file from a private bucket and returning it in a response? I havn't looked under the hood yet how strapi and koa manages files tbh,  with the express framework piping files directly to a response was quite simple actually. I see if I can PR some help here some time soon maybe.

**Comment by Lith** [comment]
Hi,

The latest release (4.10.1) should fixed your request :
- #165 

Thanks,
