### ISSUE TITLE
Upload files greater than 32mb  with Strapi hosted on Google Cloud Run

### ISSUE THREAD

**Issue by rg-softwares** [strapi-community/strapi-provider-upload-google-cloud-storage#152]
Would it be possible to integrate the v4 signing process for Google Cloud while uploading files greater than 32mb.

Ref: https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#client-libraries

When Strapi is hosted on Google Cloud Run you are facing the limit of 32mb per request.

Implementing the v4 signing process would bypass this issue.

Cheers

**Comment by Lith** [comment]
Hi @rg-softwares, 

Implementing the signing process will not fixed your problem, because this is a limitation of "Google App Engine" themself.
I suggest you to migrate your  "App Engine" server to a PaaS solution. You will have no limit.

Otherwise, please free to submit a PR with the implementation of the signing process.

Thanks,
